
export interface Institution {
  value: string;
  name: string;
  campuses?: string[];
}

export const INSTITUTIONS: Institution[] = [
  { value: "concordia", name: "Concordia University", campuses: ["Sir George Williams (downtown)", "Loyola"] },
  { value: "mcgill", name: "McGill University", campuses: ["Downtown", "Macdonald"] },
  { value: "polytechnique", name: "Polytechnique Montréal" },
  { value: "ets", name: "École de technologie supérieure (ÉTS)" },
  { value: "udem", name: "Université de Montréal", campuses: ["Montréal", "Laval", "Longueuil", "Saint-Hyacinthe"] },
  { value: "uqam", name: "Université du Québec à Montréal (UQAM)" },
  { value: "laval", name: "Université Laval" },
  { value: "sherbrooke", name: "Université de Sherbrooke", campuses: ["Sherbrooke", "Longueuil"] },
  { value: "bishops", name: "Bishop’s University" },
  { value: "uqac", name: "Université du Québec à Chicoutimi (UQAC)" },
  { value: "uqar", name: "Université du Québec à Rimouski (UQAR)", campuses: ["Rimouski", "Lévis"] },
  { value: "uqtr", name: "Université du Québec à Trois-Rivières (UQTR)" },
  { value: "uqo", name: "Université du Québec en Outaouais (UQO)", campuses: ["Gatineau", "Saint-Jérôme"] },
  { value: "uqat", name: "Université du Québec en Abitibi-Témiscamingue (UQAT)" },
  { value: "hec", name: "HEC Montréal" },
  { value: "inrs", name: "Institut national de la recherche scientifique (INRS)" },
  { value: "teluq", name: "Université TÉLUQ" },

  { value: "dawson", name: "Dawson College" },
  { value: "vanier", name: "Vanier College" },
  { value: "john-abbott", name: "John Abbott College" },
  { value: "marianopolis", name: "Marianopolis College" },
  { value: "champlain", name: "Champlain Regional College", campuses: ["Saint-Lambert", "Lennoxville", "St. Lawrence"] },
  { value: "heritage", name: "Heritage College" },
  { value: "cegep-vieux-montreal", name: "Cégep du Vieux Montréal" },
  { value: "college-de-maisonneuve", name: "Collège de Maisonneuve" },
  { value: "college-ahuntsic", name: "Collège Ahuntsic" },
  { value: "college-rosemont", name: "Collège de Rosemont" },
  { value: "cegep-marie-victorin", name: "Cégep Marie-Victorin" },
  { value: "college-bois-de-boulogne", name: "Collège de Bois-de-Boulogne" },
  { value: "cegep-saint-laurent", name: "Cégep de Saint-Laurent" },
  { value: "college-montmorency", name: "Collège Montmorency" },
  { value: "college-edouard-montpetit", name: "Cégep Édouard-Montpetit" },
  { value: "cegep-andre-laurendeau", name: "Cégep André-Laurendeau" },
  { value: "college-lionel-groulx", name: "Collège Lionel-Groulx" },
  { value: "cegep-saint-jerome", name: "Cégep de Saint-Jérôme" },
  { value: "cegep-limoilou", name: "Cégep Limoilou" },
  { value: "cegep-sainte-foy", name: "Cégep de Sainte-Foy" },
  { value: "cegep-garneau", name: "Cégep Garneau" },
  { value: "cegep-sherbrooke", name: "Cégep de Sherbrooke" },
  { value: "cegep-outaouais", name: "Cégep de l’Outaouais" },
  { value: "cegep-trois-rivieres", name: "Cégep de Trois-Rivières" },
  { value: "cegep-chicoutimi", name: "Cégep de Chicoutimi" },
  { value: "college-lasalle", name: "LaSalle College" },

  { value: "waterloo", name: "University of Waterloo" },
  { value: "uoft", name: "University of Toronto", campuses: ["St. George", "Mississauga", "Scarborough"] },
  { value: "york", name: "York University", campuses: ["Keele", "Glendon", "Markham"] },
  { value: "tmu", name: "Toronto Metropolitan University" },
  { value: "uottawa", name: "University of Ottawa" },
  { value: "carleton", name: "Carleton University" },
  { value: "queens", name: "Queen’s University" },
  { value: "western", name: "Western University" },
  { value: "mcmaster", name: "McMaster University" },
  { value: "guelph", name: "University of Guelph" },
  { value: "laurier", name: "Wilfrid Laurier University", campuses: ["Waterloo", "Brantford", "Milton"] },
  { value: "ontario-tech", name: "Ontario Tech University" },
  { value: "brock", name: "Brock University" },
  { value: "windsor", name: "University of Windsor" },
  { value: "lakehead", name: "Lakehead University", campuses: ["Thunder Bay", "Orillia"] },
  { value: "laurentian", name: "Laurentian University" },
  { value: "trent", name: "Trent University", campuses: ["Peterborough", "Durham GTA"] },
  { value: "nipissing", name: "Nipissing University" },
  { value: "algoma", name: "Algoma University" },
  { value: "ocad", name: "OCAD University" },
  { value: "uofo", name: "Université de l’Ontario français" },
  { value: "seneca", name: "Seneca Polytechnic" },
  { value: "humber", name: "Humber Polytechnic" },
  { value: "sheridan", name: "Sheridan College" },
  { value: "george-brown", name: "George Brown Polytechnic" },
  { value: "centennial", name: "Centennial College" },
  { value: "conestoga", name: "Conestoga College" },
  { value: "algonquin", name: "Algonquin College" },
  { value: "la-cite", name: "La Cité collégiale" },
  { value: "mohawk", name: "Mohawk College" },
  { value: "fanshawe", name: "Fanshawe College" },
  { value: "durham-college", name: "Durham College" },

  { value: "dalhousie", name: "Dalhousie University" },
  { value: "unb", name: "University of New Brunswick", campuses: ["Fredericton", "Saint John"] },
  { value: "umoncton", name: "Université de Moncton", campuses: ["Moncton", "Edmundston", "Shippagan"] },
  { value: "mun", name: "Memorial University of Newfoundland", campuses: ["St. John’s", "Grenfell"] },
  { value: "acadia", name: "Acadia University" },
  { value: "stfx", name: "St. Francis Xavier University" },
  { value: "smu", name: "Saint Mary’s University" },
  { value: "mount-allison", name: "Mount Allison University" },
  { value: "upei", name: "University of Prince Edward Island" },
  { value: "cape-breton", name: "Cape Breton University" },
  { value: "nscc", name: "Nova Scotia Community College" },

  { value: "manitoba", name: "University of Manitoba" },
  { value: "uwinnipeg", name: "University of Winnipeg" },
  { value: "usask", name: "University of Saskatchewan" },
  { value: "uregina", name: "University of Regina" },
  { value: "ucalgary", name: "University of Calgary" },
  { value: "ualberta", name: "University of Alberta", campuses: ["North (Edmonton)", "Augustana", "Saint-Jean"] },
  { value: "mru", name: "Mount Royal University" },
  { value: "macewan", name: "MacEwan University" },
  { value: "ulethbridge", name: "University of Lethbridge" },
  { value: "sait", name: "SAIT" },
  { value: "nait", name: "NAIT" },
  { value: "yukon", name: "Yukon University" },

  { value: "ubc", name: "University of British Columbia", campuses: ["Vancouver", "Okanagan"] },
  { value: "sfu", name: "Simon Fraser University", campuses: ["Burnaby", "Surrey", "Vancouver"] },
  { value: "uvic", name: "University of Victoria" },
  { value: "unbc", name: "University of Northern British Columbia" },
  { value: "tru", name: "Thompson Rivers University" },
  { value: "bcit", name: "British Columbia Institute of Technology (BCIT)" },
  { value: "kpu", name: "Kwantlen Polytechnic University" },
  { value: "langara", name: "Langara College" },
  { value: "douglas", name: "Douglas College" },
  { value: "capilano", name: "Capilano University" },
  { value: "ufv", name: "University of the Fraser Valley" },
  { value: "ecuad", name: "Emily Carr University of Art + Design" },

  { value: "mit", name: "Massachusetts Institute of Technology" },
  { value: "cmu", name: "Carnegie Mellon University" },
  { value: "cornell", name: "Cornell University" },
  { value: "rit", name: "Rochester Institute of Technology" },
  { value: "uvm", name: "University of Vermont" },
  { value: "buffalo", name: "University at Buffalo" },
  { value: "northeastern", name: "Northeastern University" },
];

export interface InstitutionCity {
  city: string;
  /** ISO subdivision code, as country-state-city and /api/demographics expect. */
  region: string;
  country: string;
}

/**
 * Where each school's main campus is, so the travel question can start from
 * the school's city. City names are spelled exactly as country-state-city has
 * them (Montréal, Québec) - /api/locations looks them up by that name.
 */
const INSTITUTION_CITIES: Record<string, InstitutionCity> = {
  concordia: { city: "Montréal", region: "QC", country: "CA" },
  mcgill: { city: "Montréal", region: "QC", country: "CA" },
  polytechnique: { city: "Montréal", region: "QC", country: "CA" },
  ets: { city: "Montréal", region: "QC", country: "CA" },
  udem: { city: "Montréal", region: "QC", country: "CA" },
  uqam: { city: "Montréal", region: "QC", country: "CA" },
  laval: { city: "Québec", region: "QC", country: "CA" },
  sherbrooke: { city: "Sherbrooke", region: "QC", country: "CA" },
  bishops: { city: "Sherbrooke", region: "QC", country: "CA" },
  uqac: { city: "Saguenay", region: "QC", country: "CA" },
  uqar: { city: "Rimouski", region: "QC", country: "CA" },
  uqtr: { city: "Trois-Rivières", region: "QC", country: "CA" },
  uqo: { city: "Gatineau", region: "QC", country: "CA" },
  uqat: { city: "Rouyn-Noranda", region: "QC", country: "CA" },
  hec: { city: "Montréal", region: "QC", country: "CA" },
  inrs: { city: "Québec", region: "QC", country: "CA" },
  teluq: { city: "Québec", region: "QC", country: "CA" },
  dawson: { city: "Montréal", region: "QC", country: "CA" },
  vanier: { city: "Montréal", region: "QC", country: "CA" },
  "john-abbott": { city: "Sainte-Anne-de-Bellevue", region: "QC", country: "CA" },
  marianopolis: { city: "Montréal", region: "QC", country: "CA" },
  champlain: { city: "Longueuil", region: "QC", country: "CA" },
  heritage: { city: "Gatineau", region: "QC", country: "CA" },
  "cegep-vieux-montreal": { city: "Montréal", region: "QC", country: "CA" },
  "college-de-maisonneuve": { city: "Montréal", region: "QC", country: "CA" },
  "college-ahuntsic": { city: "Montréal", region: "QC", country: "CA" },
  "college-rosemont": { city: "Montréal", region: "QC", country: "CA" },
  "cegep-marie-victorin": { city: "Montréal", region: "QC", country: "CA" },
  "college-bois-de-boulogne": { city: "Montréal", region: "QC", country: "CA" },
  "cegep-saint-laurent": { city: "Montréal", region: "QC", country: "CA" },
  "college-montmorency": { city: "Laval", region: "QC", country: "CA" },
  "college-edouard-montpetit": { city: "Longueuil", region: "QC", country: "CA" },
  "cegep-andre-laurendeau": { city: "Montréal", region: "QC", country: "CA" },
  "college-lionel-groulx": { city: "Sainte-Thérèse", region: "QC", country: "CA" },
  "cegep-saint-jerome": { city: "Saint-Jérôme", region: "QC", country: "CA" },
  "cegep-limoilou": { city: "Québec", region: "QC", country: "CA" },
  "cegep-sainte-foy": { city: "Québec", region: "QC", country: "CA" },
  "cegep-garneau": { city: "Québec", region: "QC", country: "CA" },
  "cegep-sherbrooke": { city: "Sherbrooke", region: "QC", country: "CA" },
  "cegep-outaouais": { city: "Gatineau", region: "QC", country: "CA" },
  "cegep-trois-rivieres": { city: "Trois-Rivières", region: "QC", country: "CA" },
  "cegep-chicoutimi": { city: "Saguenay", region: "QC", country: "CA" },
  "college-lasalle": { city: "Montréal", region: "QC", country: "CA" },
  waterloo: { city: "Waterloo", region: "ON", country: "CA" },
  uoft: { city: "Toronto", region: "ON", country: "CA" },
  york: { city: "Toronto", region: "ON", country: "CA" },
  tmu: { city: "Toronto", region: "ON", country: "CA" },
  uottawa: { city: "Ottawa", region: "ON", country: "CA" },
  carleton: { city: "Ottawa", region: "ON", country: "CA" },
  queens: { city: "Kingston", region: "ON", country: "CA" },
  western: { city: "London", region: "ON", country: "CA" },
  mcmaster: { city: "Hamilton", region: "ON", country: "CA" },
  guelph: { city: "Guelph", region: "ON", country: "CA" },
  laurier: { city: "Waterloo", region: "ON", country: "CA" },
  "ontario-tech": { city: "Oshawa", region: "ON", country: "CA" },
  brock: { city: "St. Catharines", region: "ON", country: "CA" },
  windsor: { city: "Windsor", region: "ON", country: "CA" },
  lakehead: { city: "Thunder Bay", region: "ON", country: "CA" },
  laurentian: { city: "Greater Sudbury", region: "ON", country: "CA" },
  trent: { city: "Peterborough", region: "ON", country: "CA" },
  nipissing: { city: "North Bay", region: "ON", country: "CA" },
  algoma: { city: "Sault Ste. Marie", region: "ON", country: "CA" },
  ocad: { city: "Toronto", region: "ON", country: "CA" },
  uofo: { city: "Toronto", region: "ON", country: "CA" },
  seneca: { city: "Toronto", region: "ON", country: "CA" },
  humber: { city: "Toronto", region: "ON", country: "CA" },
  sheridan: { city: "Oakville", region: "ON", country: "CA" },
  "george-brown": { city: "Toronto", region: "ON", country: "CA" },
  centennial: { city: "Toronto", region: "ON", country: "CA" },
  conestoga: { city: "Kitchener", region: "ON", country: "CA" },
  algonquin: { city: "Ottawa", region: "ON", country: "CA" },
  "la-cite": { city: "Ottawa", region: "ON", country: "CA" },
  mohawk: { city: "Hamilton", region: "ON", country: "CA" },
  fanshawe: { city: "London", region: "ON", country: "CA" },
  "durham-college": { city: "Oshawa", region: "ON", country: "CA" },
  dalhousie: { city: "Halifax", region: "NS", country: "CA" },
  unb: { city: "Fredericton", region: "NB", country: "CA" },
  umoncton: { city: "Moncton", region: "NB", country: "CA" },
  mun: { city: "St. John's", region: "NL", country: "CA" },
  acadia: { city: "Wolfville", region: "NS", country: "CA" },
  stfx: { city: "Antigonish", region: "NS", country: "CA" },
  smu: { city: "Halifax", region: "NS", country: "CA" },
  "mount-allison": { city: "Sackville", region: "NB", country: "CA" },
  upei: { city: "Charlottetown", region: "PE", country: "CA" },
  "cape-breton": { city: "Sydney", region: "NS", country: "CA" },
  nscc: { city: "Halifax", region: "NS", country: "CA" },
  manitoba: { city: "Winnipeg", region: "MB", country: "CA" },
  uwinnipeg: { city: "Winnipeg", region: "MB", country: "CA" },
  usask: { city: "Saskatoon", region: "SK", country: "CA" },
  uregina: { city: "Regina", region: "SK", country: "CA" },
  ucalgary: { city: "Calgary", region: "AB", country: "CA" },
  ualberta: { city: "Edmonton", region: "AB", country: "CA" },
  mru: { city: "Calgary", region: "AB", country: "CA" },
  macewan: { city: "Edmonton", region: "AB", country: "CA" },
  ulethbridge: { city: "Lethbridge", region: "AB", country: "CA" },
  sait: { city: "Calgary", region: "AB", country: "CA" },
  nait: { city: "Edmonton", region: "AB", country: "CA" },
  yukon: { city: "Whitehorse", region: "YT", country: "CA" },
  ubc: { city: "Vancouver", region: "BC", country: "CA" },
  sfu: { city: "Burnaby", region: "BC", country: "CA" },
  uvic: { city: "Victoria", region: "BC", country: "CA" },
  unbc: { city: "Prince George", region: "BC", country: "CA" },
  tru: { city: "Kamloops", region: "BC", country: "CA" },
  bcit: { city: "Burnaby", region: "BC", country: "CA" },
  kpu: { city: "Surrey", region: "BC", country: "CA" },
  langara: { city: "Vancouver", region: "BC", country: "CA" },
  douglas: { city: "New Westminster", region: "BC", country: "CA" },
  capilano: { city: "North Vancouver", region: "BC", country: "CA" },
  ufv: { city: "Abbotsford", region: "BC", country: "CA" },
  ecuad: { city: "Vancouver", region: "BC", country: "CA" },
  mit: { city: "Cambridge", region: "MA", country: "US" },
  cmu: { city: "Pittsburgh", region: "PA", country: "US" },
  cornell: { city: "Ithaca", region: "NY", country: "US" },
  rit: { city: "Rochester", region: "NY", country: "US" },
  uvm: { city: "Burlington", region: "VT", country: "US" },
  buffalo: { city: "Buffalo", region: "NY", country: "US" },
  northeastern: { city: "Boston", region: "MA", country: "US" },
};

export const institutionCity = (value: string): InstitutionCity | null =>
  INSTITUTION_CITIES[value] ?? null;

/** Schools with a head delegate this year: the only options in the delegation picker. */
export const DELEGATION_SCHOOLS: string[] = [
  "carleton",
  "concordia",
  "john-abbott",
  "ontario-tech",
  "ucalgary",
  "udem",
  "guelph",
  "manitoba",
  "uottawa",
  "uregina",
  "york",
];

export const DELEGATION_INSTITUTIONS = INSTITUTIONS.filter((i) =>
  DELEGATION_SCHOOLS.includes(i.value)
).sort((a, b) => a.name.localeCompare(b.name));

export const findInstitution = (value: string) =>
  INSTITUTIONS.find((institution) => institution.value === value);
