
export interface Institution {
  value: string;
  name: string;
  campuses?: string[];
}

export const INSTITUTIONS: Institution[] = [
  { value: "concordia", name: "Concordia University", campuses: ["Sir George Williams (downtown)", "Loyola"] },
  { value: "mcgill", name: "McGill University", campuses: ["Downtown", "Macdonald"] },
  { value: "polytechnique", name: "Polytechnique Montréal" },
  { value: "ets", name: "École de technologie supérieure (ÉTS)" },
  { value: "udem", name: "Université de Montréal", campuses: ["Montréal", "Laval", "Longueuil", "Saint-Hyacinthe"] },
  { value: "uqam", name: "Université du Québec à Montréal (UQAM)" },
  { value: "laval", name: "Université Laval" },
  { value: "sherbrooke", name: "Université de Sherbrooke", campuses: ["Sherbrooke", "Longueuil"] },
  { value: "bishops", name: "Bishop’s University" },
  { value: "uqac", name: "Université du Québec à Chicoutimi (UQAC)" },
  { value: "uqar", name: "Université du Québec à Rimouski (UQAR)", campuses: ["Rimouski", "Lévis"] },
  { value: "uqtr", name: "Université du Québec à Trois-Rivières (UQTR)" },
  { value: "uqo", name: "Université du Québec en Outaouais (UQO)", campuses: ["Gatineau", "Saint-Jérôme"] },
  { value: "uqat", name: "Université du Québec en Abitibi-Témiscamingue (UQAT)" },
  { value: "hec", name: "HEC Montréal" },
  { value: "inrs", name: "Institut national de la recherche scientifique (INRS)" },
  { value: "teluq", name: "Université TÉLUQ" },

  { value: "dawson", name: "Dawson College" },
  { value: "vanier", name: "Vanier College" },
  { value: "john-abbott", name: "John Abbott College" },
  { value: "marianopolis", name: "Marianopolis College" },
  { value: "champlain", name: "Champlain Regional College", campuses: ["Saint-Lambert", "Lennoxville", "St. Lawrence"] },
  { value: "heritage", name: "Heritage College" },
  { value: "cegep-vieux-montreal", name: "Cégep du Vieux Montréal" },
  { value: "college-de-maisonneuve", name: "Collège de Maisonneuve" },
  { value: "college-ahuntsic", name: "Collège Ahuntsic" },
  { value: "college-rosemont", name: "Collège de Rosemont" },
  { value: "cegep-marie-victorin", name: "Cégep Marie-Victorin" },
  { value: "college-bois-de-boulogne", name: "Collège de Bois-de-Boulogne" },
  { value: "cegep-saint-laurent", name: "Cégep de Saint-Laurent" },
  { value: "college-montmorency", name: "Collège Montmorency" },
  { value: "college-edouard-montpetit", name: "Cégep Édouard-Montpetit" },
  { value: "cegep-andre-laurendeau", name: "Cégep André-Laurendeau" },
  { value: "college-lionel-groulx", name: "Collège Lionel-Groulx" },
  { value: "cegep-saint-jerome", name: "Cégep de Saint-Jérôme" },
  { value: "cegep-limoilou", name: "Cégep Limoilou" },
  { value: "cegep-sainte-foy", name: "Cégep de Sainte-Foy" },
  { value: "cegep-garneau", name: "Cégep Garneau" },
  { value: "cegep-sherbrooke", name: "Cégep de Sherbrooke" },
  { value: "cegep-outaouais", name: "Cégep de l’Outaouais" },
  { value: "cegep-trois-rivieres", name: "Cégep de Trois-Rivières" },
  { value: "cegep-chicoutimi", name: "Cégep de Chicoutimi" },
  { value: "college-lasalle", name: "LaSalle College" },

  { value: "waterloo", name: "University of Waterloo" },
  { value: "uoft", name: "University of Toronto", campuses: ["St. George", "Mississauga", "Scarborough"] },
  { value: "york", name: "York University", campuses: ["Keele", "Glendon", "Markham"] },
  { value: "tmu", name: "Toronto Metropolitan University" },
  { value: "uottawa", name: "University of Ottawa" },
  { value: "carleton", name: "Carleton University" },
  { value: "queens", name: "Queen’s University" },
  { value: "western", name: "Western University" },
  { value: "mcmaster", name: "McMaster University" },
  { value: "guelph", name: "University of Guelph" },
  { value: "laurier", name: "Wilfrid Laurier University", campuses: ["Waterloo", "Brantford", "Milton"] },
  { value: "ontario-tech", name: "Ontario Tech University" },
  { value: "brock", name: "Brock University" },
  { value: "windsor", name: "University of Windsor" },
  { value: "lakehead", name: "Lakehead University", campuses: ["Thunder Bay", "Orillia"] },
  { value: "laurentian", name: "Laurentian University" },
  { value: "trent", name: "Trent University", campuses: ["Peterborough", "Durham GTA"] },
  { value: "nipissing", name: "Nipissing University" },
  { value: "algoma", name: "Algoma University" },
  { value: "ocad", name: "OCAD University" },
  { value: "uofo", name: "Université de l’Ontario français" },
  { value: "seneca", name: "Seneca Polytechnic" },
  { value: "humber", name: "Humber Polytechnic" },
  { value: "sheridan", name: "Sheridan College" },
  { value: "george-brown", name: "George Brown Polytechnic" },
  { value: "centennial", name: "Centennial College" },
  { value: "conestoga", name: "Conestoga College" },
  { value: "algonquin", name: "Algonquin College" },
  { value: "la-cite", name: "La Cité collégiale" },
  { value: "mohawk", name: "Mohawk College" },
  { value: "fanshawe", name: "Fanshawe College" },
  { value: "durham-college", name: "Durham College" },

  { value: "dalhousie", name: "Dalhousie University" },
  { value: "unb", name: "University of New Brunswick", campuses: ["Fredericton", "Saint John"] },
  { value: "umoncton", name: "Université de Moncton", campuses: ["Moncton", "Edmundston", "Shippagan"] },
  { value: "mun", name: "Memorial University of Newfoundland", campuses: ["St. John’s", "Grenfell"] },
  { value: "acadia", name: "Acadia University" },
  { value: "stfx", name: "St. Francis Xavier University" },
  { value: "smu", name: "Saint Mary’s University" },
  { value: "mount-allison", name: "Mount Allison University" },
  { value: "upei", name: "University of Prince Edward Island" },
  { value: "cape-breton", name: "Cape Breton University" },
  { value: "nscc", name: "Nova Scotia Community College" },

  { value: "manitoba", name: "University of Manitoba" },
  { value: "uwinnipeg", name: "University of Winnipeg" },
  { value: "usask", name: "University of Saskatchewan" },
  { value: "uregina", name: "University of Regina" },
  { value: "ucalgary", name: "University of Calgary" },
  { value: "ualberta", name: "University of Alberta", campuses: ["North (Edmonton)", "Augustana", "Saint-Jean"] },
  { value: "mru", name: "Mount Royal University" },
  { value: "macewan", name: "MacEwan University" },
  { value: "ulethbridge", name: "University of Lethbridge" },
  { value: "sait", name: "SAIT" },
  { value: "nait", name: "NAIT" },
  { value: "yukon", name: "Yukon University" },

  { value: "ubc", name: "University of British Columbia", campuses: ["Vancouver", "Okanagan"] },
  { value: "sfu", name: "Simon Fraser University", campuses: ["Burnaby", "Surrey", "Vancouver"] },
  { value: "uvic", name: "University of Victoria" },
  { value: "unbc", name: "University of Northern British Columbia" },
  { value: "tru", name: "Thompson Rivers University" },
  { value: "bcit", name: "British Columbia Institute of Technology (BCIT)" },
  { value: "kpu", name: "Kwantlen Polytechnic University" },
  { value: "langara", name: "Langara College" },
  { value: "douglas", name: "Douglas College" },
  { value: "capilano", name: "Capilano University" },
  { value: "ufv", name: "University of the Fraser Valley" },
  { value: "ecuad", name: "Emily Carr University of Art + Design" },

  { value: "mit", name: "Massachusetts Institute of Technology" },
  { value: "cmu", name: "Carnegie Mellon University" },
  { value: "cornell", name: "Cornell University" },
  { value: "rit", name: "Rochester Institute of Technology" },
  { value: "uvm", name: "University of Vermont" },
  { value: "buffalo", name: "University at Buffalo" },
  { value: "northeastern", name: "Northeastern University" },
];

/** Schools with a head delegate this year: the only options in the delegation picker. */
export const DELEGATION_SCHOOLS: string[] = [
  "carleton",
  "concordia",
  "john-abbott",
  "ontario-tech",
  "ucalgary",
  "udem",
  "guelph",
  "manitoba",
  "uottawa",
  "uregina",
  "york",
];

export const DELEGATION_INSTITUTIONS = INSTITUTIONS.filter((i) =>
  DELEGATION_SCHOOLS.includes(i.value)
).sort((a, b) => a.name.localeCompare(b.name));

export const findInstitution = (value: string) =>
  INSTITUTIONS.find((institution) => institution.value === value);
